### ISSUE TITLE
Plans to support Contentful v10

### ISSUE THREAD

**Issue by spiceee** [ninetailed-inc/ninetailed-examples#41]
Hi,

Sorry, I could not find a repo for `@ninetailed/experience.js-utils-contentful`. Are there any plans to bump the support to work with the latest major Contentful library? (`~ 10.4.0`)

Thanks,

Fabio.

**Comment by BraunreutherA** [comment]
Hi @spiceee, yes we're updating the Contentful utility library soon. I'll add an update here, as soon as this is done.

**Comment by BraunreutherA** [comment]
Additionally, the `@ninetailed/experience.js-utils-contentful` does work with the contentful version 10.4. The examples just don't use it cause of a typescript type change.

**Comment by spiceee** [comment]
@BraunreutherA It currently breaks our build because of the dependency conflict. We are at `contentful@"^10.2.0"`.

**Comment by BraunreutherA** [comment]
Hi @spiceee we've updated the `@ninetailed/experience.js-utils-contentful` package to use the `contentful` library only for tests anymore and thus is a devDependency instead of a peerDependency now.
This change is added in version `4.2.5`.

It'd be great if you could let us know if that solved your issue. Thank you!

**Comment by spiceee** [comment]
@BraunreutherA works now, thanks! (It was working before with `--legacy-peer-deps`, just so you know).
